version: '3.9'

services:
  api:
    container_name: my_api_container
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: my_db_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'notes'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
